### ISSUE TITLE
Model centric FL

### ISSUE THREAD

**Issue by rhobro** [OpenMined/syft_experimental#5]
## Question
Does this Rust implementation of Syft support being a client to model centric FL yet and when can we expect it to become production like the kotlin and swift counterparts?

## Further Information
I have a use case which requires me to run a server which will act as a client to model centric FL but needs to be higher performance than Python.

**Comment by rhobro** [comment]
Will the rust project also be able to act as the server side grid?

**Comment by madhavajay** [comment]
@rhobro Sorry, this experimental Rust repo was purely for iterating on some ideas for doing a Rust Core with multiple front ends. This code base will not be maintained. The main `PySyft` repo is still very active and we are working on some new functionality. Performance is something we will definitely be addressing in the not too distant future.
